GET http://localhost:27017/prueba/producto
###
GET http://localhost:27017/producto
###
POST http://localhost:3000/subscribers
{
    "name": "amazing person",
    "subscrbedToChannel": "some channel"
}
